// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0-rc.1
// 	protoc        v3.21.4
// source: money.proto

package index

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 用于表示价格，金额相关的
type Money struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UnscaledValue int64   `protobuf:"varint,1,opt,name=unscaledValue,proto3" json:"unscaledValue,omitempty"`
	Scale         int32   `protobuf:"varint,2,opt,name=scale,proto3" json:"scale,omitempty"`
	Coin          string  `protobuf:"bytes,3,opt,name=coin,proto3" json:"coin,omitempty"`
	StrValue      *string `protobuf:"bytes,4,opt,name=strValue,proto3,oneof" json:"strValue,omitempty"`
}

func (x *Money) Reset() {
	*x = Money{}
	if protoimpl.UnsafeEnabled {
		mi := &file_money_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Money) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Money) ProtoMessage() {}

func (x *Money) ProtoReflect() protoreflect.Message {
	mi := &file_money_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Money.ProtoReflect.Descriptor instead.
func (*Money) Descriptor() ([]byte, []int) {
	return file_money_proto_rawDescGZIP(), []int{0}
}

func (x *Money) GetUnscaledValue() int64 {
	if x != nil {
		return x.UnscaledValue
	}
	return 0
}

func (x *Money) GetScale() int32 {
	if x != nil {
		return x.Scale
	}
	return 0
}

func (x *Money) GetCoin() string {
	if x != nil {
		return x.Coin
	}
	return ""
}

func (x *Money) GetStrValue() string {
	if x != nil && x.StrValue != nil {
		return *x.StrValue
	}
	return ""
}

// 表示数量相关的
type PrecisionDecimal struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UnscaledValue int64   `protobuf:"varint,1,opt,name=unscaledValue,proto3" json:"unscaledValue,omitempty"`
	Scale         int32   `protobuf:"varint,2,opt,name=scale,proto3" json:"scale,omitempty"`
	StrValue      *string `protobuf:"bytes,3,opt,name=strValue,proto3,oneof" json:"strValue,omitempty"`
}

func (x *PrecisionDecimal) Reset() {
	*x = PrecisionDecimal{}
	if protoimpl.UnsafeEnabled {
		mi := &file_money_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PrecisionDecimal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrecisionDecimal) ProtoMessage() {}

func (x *PrecisionDecimal) ProtoReflect() protoreflect.Message {
	mi := &file_money_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrecisionDecimal.ProtoReflect.Descriptor instead.
func (*PrecisionDecimal) Descriptor() ([]byte, []int) {
	return file_money_proto_rawDescGZIP(), []int{1}
}

func (x *PrecisionDecimal) GetUnscaledValue() int64 {
	if x != nil {
		return x.UnscaledValue
	}
	return 0
}

func (x *PrecisionDecimal) GetScale() int32 {
	if x != nil {
		return x.Scale
	}
	return 0
}

func (x *PrecisionDecimal) GetStrValue() string {
	if x != nil && x.StrValue != nil {
		return *x.StrValue
	}
	return ""
}

var File_money_proto protoreflect.FileDescriptor

var file_money_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x6d, 0x6f, 0x6e, 0x65, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x85, 0x01,
	0x0a, 0x05, 0x4d, 0x6f, 0x6e, 0x65, 0x79, 0x12, 0x24, 0x0a, 0x0d, 0x75, 0x6e, 0x73, 0x63, 0x61,
	0x6c, 0x65, 0x64, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0d,
	0x75, 0x6e, 0x73, 0x63, 0x61, 0x6c, 0x65, 0x64, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x14, 0x0a,
	0x05, 0x73, 0x63, 0x61, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x73, 0x63,
	0x61, 0x6c, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x69, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x63, 0x6f, 0x69, 0x6e, 0x12, 0x1f, 0x0a, 0x08, 0x73, 0x74, 0x72, 0x56, 0x61,
	0x6c, 0x75, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x08, 0x73, 0x74, 0x72,
	0x56, 0x61, 0x6c, 0x75, 0x65, 0x88, 0x01, 0x01, 0x42, 0x0b, 0x0a, 0x09, 0x5f, 0x73, 0x74, 0x72,
	0x56, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x7c, 0x0a, 0x10, 0x50, 0x72, 0x65, 0x63, 0x69, 0x73, 0x69,
	0x6f, 0x6e, 0x44, 0x65, 0x63, 0x69, 0x6d, 0x61, 0x6c, 0x12, 0x24, 0x0a, 0x0d, 0x75, 0x6e, 0x73,
	0x63, 0x61, 0x6c, 0x65, 0x64, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x0d, 0x75, 0x6e, 0x73, 0x63, 0x61, 0x6c, 0x65, 0x64, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12,
	0x14, 0x0a, 0x05, 0x73, 0x63, 0x61, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05,
	0x73, 0x63, 0x61, 0x6c, 0x65, 0x12, 0x1f, 0x0a, 0x08, 0x73, 0x74, 0x72, 0x56, 0x61, 0x6c, 0x75,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x08, 0x73, 0x74, 0x72, 0x56, 0x61,
	0x6c, 0x75, 0x65, 0x88, 0x01, 0x01, 0x42, 0x0b, 0x0a, 0x09, 0x5f, 0x73, 0x74, 0x72, 0x56, 0x61,
	0x6c, 0x75, 0x65, 0x42, 0x0d, 0x5a, 0x0b, 0x71, 0x75, 0x6f, 0x74, 0x65, 0x2f, 0x69, 0x6e, 0x64,
	0x65, 0x78, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_money_proto_rawDescOnce sync.Once
	file_money_proto_rawDescData = file_money_proto_rawDesc
)

func file_money_proto_rawDescGZIP() []byte {
	file_money_proto_rawDescOnce.Do(func() {
		file_money_proto_rawDescData = protoimpl.X.CompressGZIP(file_money_proto_rawDescData)
	})
	return file_money_proto_rawDescData
}

var file_money_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_money_proto_goTypes = []interface{}{
	(*Money)(nil),            // 0: Money
	(*PrecisionDecimal)(nil), // 1: PrecisionDecimal
}
var file_money_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_money_proto_init() }
func file_money_proto_init() {
	if File_money_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_money_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Money); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_money_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PrecisionDecimal); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_money_proto_msgTypes[0].OneofWrappers = []interface{}{}
	file_money_proto_msgTypes[1].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_money_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_money_proto_goTypes,
		DependencyIndexes: file_money_proto_depIdxs,
		MessageInfos:      file_money_proto_msgTypes,
	}.Build()
	File_money_proto = out.File
	file_money_proto_rawDesc = nil
	file_money_proto_goTypes = nil
	file_money_proto_depIdxs = nil
}
