// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.19.4
// source: ImpSmpService.proto

package imp

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SmpGroupQueryReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid   int64  `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`    // 用户UID (非必传，不传返回全量smpGroup信息；uid值存在 查询uid对应机构的smp信息)
	ReqId string `protobuf:"bytes,2,opt,name=reqId,proto3" json:"reqId,omitempty"` // 查询的ID，日志链路追踪使用
}

func (x *SmpGroupQueryReq) Reset() {
	*x = SmpGroupQueryReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ImpSmpService_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SmpGroupQueryReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SmpGroupQueryReq) ProtoMessage() {}

func (x *SmpGroupQueryReq) ProtoReflect() protoreflect.Message {
	mi := &file_ImpSmpService_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SmpGroupQueryReq.ProtoReflect.Descriptor instead.
func (*SmpGroupQueryReq) Descriptor() ([]byte, []int) {
	return file_ImpSmpService_proto_rawDescGZIP(), []int{0}
}

func (x *SmpGroupQueryReq) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *SmpGroupQueryReq) GetReqId() string {
	if x != nil {
		return x.ReqId
	}
	return ""
}

type SmpGroupQueryResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SmpGroups []*SmpGroupConfigItem `protobuf:"bytes,1,rep,name=smp_groups,json=smpGroups,proto3" json:"smp_groups,omitempty"`
	RetCode   string                `protobuf:"bytes,2,opt,name=retCode,proto3" json:"retCode,omitempty"` // 0 : success
	RetMsg    string                `protobuf:"bytes,3,opt,name=retMsg,proto3" json:"retMsg,omitempty"`   // 失败信息
	ReqId     string                `protobuf:"bytes,4,opt,name=reqId,proto3" json:"reqId,omitempty"`     // 请求reqId
}

func (x *SmpGroupQueryResp) Reset() {
	*x = SmpGroupQueryResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ImpSmpService_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SmpGroupQueryResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SmpGroupQueryResp) ProtoMessage() {}

func (x *SmpGroupQueryResp) ProtoReflect() protoreflect.Message {
	mi := &file_ImpSmpService_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SmpGroupQueryResp.ProtoReflect.Descriptor instead.
func (*SmpGroupQueryResp) Descriptor() ([]byte, []int) {
	return file_ImpSmpService_proto_rawDescGZIP(), []int{1}
}

func (x *SmpGroupQueryResp) GetSmpGroups() []*SmpGroupConfigItem {
	if x != nil {
		return x.SmpGroups
	}
	return nil
}

func (x *SmpGroupQueryResp) GetRetCode() string {
	if x != nil {
		return x.RetCode
	}
	return ""
}

func (x *SmpGroupQueryResp) GetRetMsg() string {
	if x != nil {
		return x.RetMsg
	}
	return ""
}

func (x *SmpGroupQueryResp) GetReqId() string {
	if x != nil {
		return x.ReqId
	}
	return ""
}

type SmpGroupConfigItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	InstId       string          `protobuf:"bytes,1,opt,name=instId,proto3" json:"instId,omitempty"`             // 机构ID
	InstSmpGroup []*SmpGroupItem `protobuf:"bytes,2,rep,name=instSmpGroup,proto3" json:"instSmpGroup,omitempty"` // 机构ID对应的smp配置信息
}

func (x *SmpGroupConfigItem) Reset() {
	*x = SmpGroupConfigItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ImpSmpService_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SmpGroupConfigItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SmpGroupConfigItem) ProtoMessage() {}

func (x *SmpGroupConfigItem) ProtoReflect() protoreflect.Message {
	mi := &file_ImpSmpService_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SmpGroupConfigItem.ProtoReflect.Descriptor instead.
func (*SmpGroupConfigItem) Descriptor() ([]byte, []int) {
	return file_ImpSmpService_proto_rawDescGZIP(), []int{2}
}

func (x *SmpGroupConfigItem) GetInstId() string {
	if x != nil {
		return x.InstId
	}
	return ""
}

func (x *SmpGroupConfigItem) GetInstSmpGroup() []*SmpGroupItem {
	if x != nil {
		return x.InstSmpGroup
	}
	return nil
}

type SmpGroupItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SmpGroup int32   `protobuf:"varint,1,opt,name=smpGroup,proto3" json:"smpGroup,omitempty"` // smpGroupId
	Uids     []int64 `protobuf:"varint,2,rep,packed,name=uids,proto3" json:"uids,omitempty"`  // smpGroup uids
}

func (x *SmpGroupItem) Reset() {
	*x = SmpGroupItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ImpSmpService_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SmpGroupItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SmpGroupItem) ProtoMessage() {}

func (x *SmpGroupItem) ProtoReflect() protoreflect.Message {
	mi := &file_ImpSmpService_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SmpGroupItem.ProtoReflect.Descriptor instead.
func (*SmpGroupItem) Descriptor() ([]byte, []int) {
	return file_ImpSmpService_proto_rawDescGZIP(), []int{3}
}

func (x *SmpGroupItem) GetSmpGroup() int32 {
	if x != nil {
		return x.SmpGroup
	}
	return 0
}

func (x *SmpGroupItem) GetUids() []int64 {
	if x != nil {
		return x.Uids
	}
	return nil
}

var File_ImpSmpService_proto protoreflect.FileDescriptor

var file_ImpSmpService_proto_rawDesc = []byte{
	0x0a, 0x13, 0x49, 0x6d, 0x70, 0x53, 0x6d, 0x70, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x3a, 0x0a, 0x10, 0x53, 0x6d, 0x70, 0x47, 0x72, 0x6f, 0x75,
	0x70, 0x51, 0x75, 0x65, 0x72, 0x79, 0x52, 0x65, 0x71, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x72,
	0x65, 0x71, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x72, 0x65, 0x71, 0x49,
	0x64, 0x22, 0x8f, 0x01, 0x0a, 0x11, 0x53, 0x6d, 0x70, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x51, 0x75,
	0x65, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x12, 0x32, 0x0a, 0x0a, 0x73, 0x6d, 0x70, 0x5f, 0x67,
	0x72, 0x6f, 0x75, 0x70, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x53, 0x6d,
	0x70, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x49, 0x74, 0x65, 0x6d,
	0x52, 0x09, 0x73, 0x6d, 0x70, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x72,
	0x65, 0x74, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x72, 0x65,
	0x74, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x74, 0x4d, 0x73, 0x67, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x74, 0x4d, 0x73, 0x67, 0x12, 0x14, 0x0a,
	0x05, 0x72, 0x65, 0x71, 0x49, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x72, 0x65,
	0x71, 0x49, 0x64, 0x22, 0x5f, 0x0a, 0x12, 0x53, 0x6d, 0x70, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x43,
	0x6f, 0x6e, 0x66, 0x69, 0x67, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x16, 0x0a, 0x06, 0x69, 0x6e, 0x73,
	0x74, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x69, 0x6e, 0x73, 0x74, 0x49,
	0x64, 0x12, 0x31, 0x0a, 0x0c, 0x69, 0x6e, 0x73, 0x74, 0x53, 0x6d, 0x70, 0x47, 0x72, 0x6f, 0x75,
	0x70, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x53, 0x6d, 0x70, 0x47, 0x72, 0x6f,
	0x75, 0x70, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x0c, 0x69, 0x6e, 0x73, 0x74, 0x53, 0x6d, 0x70, 0x47,
	0x72, 0x6f, 0x75, 0x70, 0x22, 0x3e, 0x0a, 0x0c, 0x53, 0x6d, 0x70, 0x47, 0x72, 0x6f, 0x75, 0x70,
	0x49, 0x74, 0x65, 0x6d, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x6d, 0x70, 0x47, 0x72, 0x6f, 0x75, 0x70,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x73, 0x6d, 0x70, 0x47, 0x72, 0x6f, 0x75, 0x70,
	0x12, 0x12, 0x0a, 0x04, 0x75, 0x69, 0x64, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x03, 0x52, 0x04,
	0x75, 0x69, 0x64, 0x73, 0x32, 0x47, 0x0a, 0x0d, 0x49, 0x6d, 0x70, 0x53, 0x6d, 0x70, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x36, 0x0a, 0x0d, 0x53, 0x6d, 0x70, 0x47, 0x72, 0x6f, 0x75,
	0x70, 0x51, 0x75, 0x65, 0x72, 0x79, 0x12, 0x11, 0x2e, 0x53, 0x6d, 0x70, 0x47, 0x72, 0x6f, 0x75,
	0x70, 0x51, 0x75, 0x65, 0x72, 0x79, 0x52, 0x65, 0x71, 0x1a, 0x12, 0x2e, 0x53, 0x6d, 0x70, 0x47,
	0x72, 0x6f, 0x75, 0x70, 0x51, 0x75, 0x65, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x42, 0x07, 0x5a,
	0x05, 0x2e, 0x2f, 0x69, 0x6d, 0x70, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_ImpSmpService_proto_rawDescOnce sync.Once
	file_ImpSmpService_proto_rawDescData = file_ImpSmpService_proto_rawDesc
)

func file_ImpSmpService_proto_rawDescGZIP() []byte {
	file_ImpSmpService_proto_rawDescOnce.Do(func() {
		file_ImpSmpService_proto_rawDescData = protoimpl.X.CompressGZIP(file_ImpSmpService_proto_rawDescData)
	})
	return file_ImpSmpService_proto_rawDescData
}

var file_ImpSmpService_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_ImpSmpService_proto_goTypes = []interface{}{
	(*SmpGroupQueryReq)(nil),   // 0: SmpGroupQueryReq
	(*SmpGroupQueryResp)(nil),  // 1: SmpGroupQueryResp
	(*SmpGroupConfigItem)(nil), // 2: SmpGroupConfigItem
	(*SmpGroupItem)(nil),       // 3: SmpGroupItem
}
var file_ImpSmpService_proto_depIdxs = []int32{
	2, // 0: SmpGroupQueryResp.smp_groups:type_name -> SmpGroupConfigItem
	3, // 1: SmpGroupConfigItem.instSmpGroup:type_name -> SmpGroupItem
	0, // 2: ImpSmpService.SmpGroupQuery:input_type -> SmpGroupQueryReq
	1, // 3: ImpSmpService.SmpGroupQuery:output_type -> SmpGroupQueryResp
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_ImpSmpService_proto_init() }
func file_ImpSmpService_proto_init() {
	if File_ImpSmpService_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_ImpSmpService_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SmpGroupQueryReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ImpSmpService_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SmpGroupQueryResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ImpSmpService_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SmpGroupConfigItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ImpSmpService_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SmpGroupItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_ImpSmpService_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ImpSmpService_proto_goTypes,
		DependencyIndexes: file_ImpSmpService_proto_depIdxs,
		MessageInfos:      file_ImpSmpService_proto_msgTypes,
	}.Build()
	File_ImpSmpService_proto = out.File
	file_ImpSmpService_proto_rawDesc = nil
	file_ImpSmpService_proto_goTypes = nil
	file_ImpSmpService_proto_depIdxs = nil
}
